version: '3'
services:
  web:
    image: ${NGINX_IMAGE}
    ports:
      - "80:80"
    links:
      - fluentd
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: ${LOG_OPT_TAG_PREFIX}.efk.nginx

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      - 'node.name=mynode'
      - "discovery.type=single-node"
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ports:
      - "9200:9200"
    restart: always

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    depends_on:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "2"
    restart: always

  kibana:
    image: ${KIBANA_IMAGE}
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: always
