version: '3'
services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: ${PREFIX}_es
    environment:
      - 'node.name=${PREFIX}_es'
      - "discovery.type=single-node"
      - 'bootstrap.memory_lock=false'
      - 'cluster.name=es-docker-cluster'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - "9200:9200"
    restart: unless-stopped

  fluent-bit:
    image: fluent/fluent-bit:1.5
    container_name: ${PREFIX}_fluent
    volumes:
      - ./fluent-bit/conf:/fluent-bit/etc
    depends_on:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "5140:5140/udp"
      - "2020:2020"
    logging:
        driver: "json-file"
        options:
            max-size: "100m"
            max-file: "5"
    restart: unless-stopped

  kibana:
    image: ${KIBANA_IMAGE}
    container_name: ${PREFIX}_kibana
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://${PREFIX}_es:9200
      ELASTICSEARCH_HOST: http://${PREFIX}_es:9200
    restart: unless-stopped

networks:
  default:
    external:
      name: ftd-mysql_ftd
