version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3.7-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=abc1234
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672

  rabbitmq2:
    image: rabbitmq:3.7-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=abc1234
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh","/usr/local/bin/cluster-entrypoint.sh"]

  rabbitmq3:
    image: rabbitmq:3.7-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=abc1234
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh","/usr/local/bin/cluster-entrypoint.sh"]
