version: "3"
services:
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo1
      - mongo2
      - mongo3
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER}   # Config Admin User
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}   # Config Admin Pass
    restart: unless-stopped
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.0-xenial
    expose:
      - 27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    volumes:
      - ./key/keyfile:${KEY_PATH}/keyfile
      - ./script:${SCRIPT_PATH}
      - ./data/m1:/data/db
    command: [ "--bind_ip_all", "--replSet", "rs0", "--keyFile", "${KEY_PATH}/keyfile", "--journal", "--smallfiles" ]
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.0-xenial
    volumes:
      - ./key/keyfile:${KEY_PATH}/keyfile
      - ./data/m2:/data/db
    expose:
      - 27017
    restart: unless-stopped
    command: [ "--bind_ip_all", "--replSet", "rs0", "--keyFile", "${KEY_PATH}/keyfile", "--journal", "--smallfiles" ]
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.0-xenial
    volumes:
      - ./key/keyfile:${KEY_PATH}/keyfile
      - ./data/m3:/data/db
    expose:
      - 27017
    restart: unless-stopped
    command: [ "--bind_ip_all", "--replSet", "rs0", "--keyFile", "${KEY_PATH}/keyfile", "--journal", "--smallfiles" ]
